[package]
name = "rargs"
version = "0.1.0"
edition = "2018"
authors = [ "Notidman" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
console = "0.14.1"
